version: '3'
services:
  # app:
  #   image: nextmoov/docker-app
  #   build:
  #     context: ..
  #     dockerfile: ./.devcontainer/Dockerfile-app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000"
  #   volumes:
  #     - "../src:/app/src"
  #     # - "../package.json:/app/package.json"
  #     - "../public:/app/public"
  #   command: npm run start -- --host 0.0.0.0 --port 3000
  # storybook:
  #   ports:
  #     - "6006:6006"
  #   build:
  #     context: ..
  #     dockerfile: ./.devcontainer/Dockerfile-storybook
  #   volumes:
  #     - "../src:/app/src"
  #   command: npm run storybook -- --host 0.0.0.0 --port 6006
  docz:
    image: nextmoov/docker-docz
    build:
      context: .
      dockerfile: ./Dockerfile-docz
    ports:
      - "4000:4000"
    volumes:
      - "/Users/dfl/code/uxilab/uxi/src:/app/src"
      - "/Users/dfl/code/uxilab/uxi/.docz:/app/.docz"
    command: npm run docz:dev
  # tests:
  #   build:
  #     context: ..
  #     dockerfile: ./.devcontainer/Dockerfile-app
  #   volumes:
  #     - "../src:/app/src"
  #   command: npm run test:watch
